#!/bin/bash
set -e -o pipefail

name=
pid=
pidfile=
logfile=


main() {
  local instance=
  local instances=

  while getopts n:i:I:p:l: OPTNAME; do
    case "$OPTNAME" in
      h)
        usage
        exit 0
      ;;
      n)
        name=$OPTARG
      ;;
      i)
        instance=$OPTARG
      ;;
      I)
        instances=$OPTARG
      ;;
      p)
        pidfile=$OPTARG
      ;;
      l)
        logfile=$OPTARG
      ;;
    esac
  done
  shift $(($OPTIND - 1))

  local command=$1
  shift

  if [[ "$1" == "--" ]]; then
    shift
  fi

  if [[ -z "$name" ]]; then
    name=screend
  fi
  name="$name${instance:+-$instance}"

  if [[ -z "$pidfile" ]]; then
    pidfile=$PWD
  fi
  if [[ -d "$pidfile" ]]; then
    pidfile="$pidfile/$name.pid"
  fi

  if [[ -n "$logfile" ]]; then
    if [[ -d "$logfile" ]]; then
      logfile="$logfile/$name.log"
    fi
  else
    logfile=/dev/null
  fi

  pid=$(getscreen "$name")

  case "$command" in
    start|exec)
      doit $command "$@"
    ;;
    stop|status)
      doit $command
    ;;
    monit)
      doit $command "${instances}" "$@"
    ;;
    *)
      return 1
    ;;
  esac
}


doit() {
  command=$1
  shift
  "do$command" "$@"
}

dostart() {
  [[ -z "$pid" ]]
  rm -f "$pidfile"

  local conffile=$(mktempconf screen)
  echo logfile $logfile > "$conffile"
  screen -d -m -s "$SHELL" -c "$conffile" -L -S "$name" "$0" -p "$pidfile" exec -- "$@"
  rm "$conffile"
  pid=$(getscreen "$name")
  [[ -n "$pid" ]] # die if no pid

  echo $pid > "$pidfile"
  if ! kill -0 "$pid"; then
    rm -f "$pidfile" "$pidfile.tmp"
    return 1
  fi

  if [[ ! -s "$pidfile.tmp" ]]; then
    sleep 1
  fi
  mv "$pidfile.tmp" "$pidfile"
}

dostop() {
  [[ -n "$pid" ]] || return 0

  kill $pid
}

dostatus() {
  [[ -n "$pid" ]]

  kill -0 $pid
}

doexec() {
  echo $$ > "$pidfile.tmp"
  exec "$@"
}

domonit() {
  local instances=${1:-1}
  shift

  local conffile=$(mktempconf monit)
  if [[ -f "$HOME/.monitrc" ]]; then
    cat $HOME/.monitrc > "$conffile"
  fi  
  echo "set init" >> "$conffile" 
  echo "set daemon 30" >> "$conffile"
  echo "set logfile /dev/stdout" >> "$conffile"
  if [[ -f "$HOME/.screend.monitrc" ]]; then
    cat "$HOME/.screend.monitrc" >> "$conffile"
  fi

  local self=$(readlink -f "$0")
  local i
  for i in $(seq 1 $instances); do
    local ipidfile=$(sed -e ':^/dev/null$:n;s:\([.][^.]*\)$:-'$i'\1:' <<< "$pidfile")
    local ilogfile=$(sed -e ':^/dev/null$:n;s:\([.][^.]*\)$:-'$i'\1:' <<< "$logfile")
    echo "check process $name-$i with pidfile $ipidfile" >> "$conffile"
    echo "start program = \"$self -n $name -i $i -p $ipidfile -l $ilogfile start -- $*\"" >> "$conffile"
    echo "stop program  = \"$self -n $name -i $i -p $ipidfile -l $ilogfile stop\"" >> "$conffile"
  done
  "$self" -n "$name" -p "$pidfile" -l "$logfile" start -- monit -c "$conffile"
  sleep 1
  rm "$conffile"
}


getscreen() {
  local name=$1
  screen -ls | awk -F '[ \t.]+' '$3 == "'$name'" { print $2 }' || true
}

mktempconf() {
  local name=${1:-screend}
  mktemp --tmpdir "${name}rc.XXXXXXXXXX"
}


main "$@"
exit $?

